### ISSUE TITLE
No Device found under Android 6

### ISSUE THREAD

**Issue by inxtremo** [liskin/locus-rflkt-addon#6]
Actual version 010 from GitHub crashes at start. Any further development on this Add-On?

**Comment by liskin** [comment]
Can you post details of the crash? I think I'm running the latest on my phone and it works. Unfortunately Google Play won't let me downgrade to lower API version so the latest there is 0.9 and needs some manual permission adjustment for discovery to work. Last time I checked, Wahoo library wasn't Android 6 aware so the permissions problem is here to stay, I'm afraid. But I should revert the build back to API 23 and release a new version so that avg HRM and battery widgets are there.

**Comment by inxtremo** [comment]
Hey. Thank you for the fast response. I´m, happy to see that the Add-On ist not dead. 
Further Google research had gave me the solution. I read that i have to give the app the right permissions under Android 6. After that, it works like a charme, theoretically. Because of the bad weather conditions i was not able to test it outdoor. But I´m sure it will work. 

Thanks and best regards,
Daniel

**Comment by liskin** [comment]
This should be fixed for real in https://github.com/liskin/locus-rflkt-addon/releases/tag/v0.11 and https://github.com/liskin/locus-rflkt-addon/releases/tag/v0.12
